spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true